using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Drawing;

namespace Tyrian
{
    /// <summary>
    /// This class is helper for Render.cs used for storing sprite parameters generated by Physics.cs. 
    /// Each object of this class
    /// stores information abou position, size, speed, life and visibility.
    /// </summary>
    /// 
    public sealed class Sprite
    {
        public int width; //width of sprite
        public int height; //height of sprite
        public int position_x; //position of left corner
        public int position_y; //position of top corner
        public int speed;
        public bool visible;
        public bool life;

        /// <summary>
        /// Create sprite with default dimensions 32x32px.
        /// </summary>
        public Sprite()
        {
            width = 32;
            height = 32;
            position_x = Game.width+100;
            position_y = Game.height+100;
            speed = 10;
            visible = false;
        }

        /// <summary>
        /// Create sprite with defined square dimensions.
        /// </summary>
        /// <param name="width"> sprite width</param>
        public Sprite(int width) : this()
        {
            this.width = width;
            this.height = width;
        }

        /// <summary>
        /// Create sprite with defined dimensions.
        /// </summary>
        /// <param name="width"> sprite width</param>
        /// <param name="height"> sprite height</param>
        public Sprite(int width, int height) : this(width)
        {
            this.height = height;
        }
        /// <summary>
        /// Create sprite with defined dimensions.
        /// </summary>
        /// <param name="width">sprite width</param>
        /// <param name="position_x">position of left corner</param>
        /// <param name="position_y">position of top corner</param>
        public Sprite(int width, int position_x, int position_y) : this(width)
        {
            this.position_x = position_x;
            this.position_y = position_y;
        }
        /// <summary>
        /// Create sprite with defined dimensions and specified position.
        /// </summary>
        /// <param name="width">sprite width</param>
        /// <param name="height">sprite height</param>
        /// <param name="position_x">position of left corner</param>
        /// <param name="position_y">position of top corner</param>
        public Sprite(int width, int height, int position_x, int position_y) : this(width, height)
        {
            this.position_x = position_x;
            this.position_y = position_y;
        }

        /// <summary>
        ///  Create sprite with defined square dimensions and specified position, speed and visibility.
        /// </summary>
        /// <param name="width">sprite width</param>
        /// <param name="position_x">position of left corner</param>
        /// <param name="position_y">position of top corner</param>
        /// <param name="speed">sprite speed</param>
        /// <param name="visible">sprite visibility</param>
        /// <param name="life">life state</param>
        public Sprite(int width,int position_x, int position_y, int speed, bool visible, bool life) : this(width, position_x, position_y)
        {
            this.speed = speed;
            this.visible = visible;
            this.life = life;
        }
        /// <summary>
        /// Create sprite with defined  dimensions and specified position, speed and visibility.
        /// </summary>
        /// <param name="width">sprite width</param>
        /// <param name="height">sprite height</param>
        /// <param name="position_x">position of left corner</param>
        /// <param name="position_y">position of top corner</param>
        /// <param name="speed">sprite speed</param>
        /// <param name="visible">sprite visibility</param>
        /// <param name="life">life state</param>
        public Sprite(int width, int height, int position_x, int position_y, int speed, bool visible, bool life) : this(width, height, position_x, position_y)
        {
            this.speed = speed;
            this.visible = visible;
            this.life = life;
        }
    }
}
